version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.7
    steps:
      - checkout
      - run:
        command: |
          sudo pip install pipenv
      - run:
        command: |
          pipenv install
      - store_test_results:
        path: test-results
      - store_artifacts:
        path: test-results
        destination: tr1
