version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python test.py
